ModuleCmd_Load.c(213):ERROR:105: Unable to locate a modulefile for 'anaconda/3-5.3.1'
ModuleCmd_Load.c(213):ERROR:105: Unable to locate a modulefile for 'python'
>> cuda-10.1_cudnn-7.6.5 has been loaded.
/usr/bin/python: No module named pip
/usr/bin/python: No module named pip
/usr/bin/python: No module named pip
/usr/bin/python: No module named pip
/usr/bin/python: No module named pip
/usr/bin/python: No module named pip
srun: error: saliksik-gpu-04: tasks 0-1,3-4,6,10: Exited with exit code 1
/usr/bin/python: No module named pip
/usr/bin/python: No module named pip
/usr/bin/python: No module named pip
/usr/bin/python: No module named pip
/usr/bin/python: No module named pip
/usr/bin/python: No module named pip
srun: error: saliksik-gpu-04: tasks 2,5,7-9,11: Exited with exit code 1
Fatal Python error: initfsencoding: Unable to get the locale encoding
Traceback (most recent call last):
  File "/opt/hpcc/CPU/anaconda/3-5.3.1/lib/python3.7/encodings/__init__.py", line 31, in <module>
ModuleNotFoundError: No module named 'codecs'
Fatal Python error: initfsencoding: Unable to get the locale encoding
Traceback (most recent call last):
  File "/opt/hpcc/CPU/anaconda/3-5.3.1/lib/python3.7/encodings/__init__.py", line 31, in <module>
ModuleNotFoundError: No module named 'codecs'
Fatal Python error: initfsencoding: Unable to get the locale encoding
Traceback (most recent call last):
  File "/opt/hpcc/CPU/anaconda/3-5.3.1/lib/python3.7/encodings/__init__.py", line 31, in <module>
ModuleNotFoundError: No module named 'codecs'
Fatal Python error: initfsencoding: Unable to get the locale encoding
Traceback (most recent call last):
  File "/opt/hpcc/CPU/anaconda/3-5.3.1/lib/python3.7/encodings/__init__.py", line 31, in <module>
Fatal Python error: initfsencoding: Unable to get the locale encoding
Traceback (most recent call last):
  File "/opt/hpcc/CPU/anaconda/3-5.3.1/lib/python3.7/encodings/__init__.py", line 31, in <module>
ModuleNotFoundError: No module named 'codecs'
ModuleNotFoundError: No module named 'codecs'
Fatal Python error: initfsencoding: Unable to get the locale encoding
Traceback (most recent call last):
  File "/opt/hpcc/CPU/anaconda/3-5.3.1/lib/python3.7/encodings/__init__.py", line 31, in <module>
ModuleNotFoundError: No module named 'codecs'
srun: error: saliksik-gpu-04: tasks 0,3,5,9-11: Aborted
Fatal Python error: initfsencoding: Unable to get the locale encoding
Traceback (most recent call last):
  File "/opt/hpcc/CPU/anaconda/3-5.3.1/lib/python3.7/encodings/__init__.py", line 31, in <module>
Fatal Python error: initfsencoding: Unable to get the locale encoding
Traceback (most recent call last):
  File "/opt/hpcc/CPU/anaconda/3-5.3.1/lib/python3.7/encodings/__init__.py", line 31, in <module>
Fatal Python error: initfsencoding: Unable to get the locale encoding
Traceback (most recent call last):
  File "/opt/hpcc/CPU/anaconda/3-5.3.1/lib/python3.7/encodings/__init__.py", line 31, in <module>
Fatal Python error: initfsencoding: Unable to get the locale encoding
Traceback (most recent call last):
  File "/opt/hpcc/CPU/anaconda/3-5.3.1/lib/python3.7/encodings/__init__.py", line 31, in <module>
Fatal Python error: initfsencoding: Unable to get the locale encoding
Traceback (most recent call last):
  File "/opt/hpcc/CPU/anaconda/3-5.3.1/lib/python3.7/encodings/__init__.py", line 31, in <module>
Fatal Python error: initfsencoding: Unable to get the locale encoding
Traceback (most recent call last):
  File "/opt/hpcc/CPU/anaconda/3-5.3.1/lib/python3.7/encodings/__init__.py", line 31, in <module>
ModuleNotFoundError: No module named 'codecs'
ModuleNotFoundError: No module named 'codecs'
ModuleNotFoundError: No module named 'codecs'
ModuleNotFoundError: No module named 'codecs'
ModuleNotFoundError: No module named 'codecs'
ModuleNotFoundError: No module named 'codecs'
srun: error: saliksik-gpu-04: tasks 1-2,4,6-8: Aborted
Fatal Python error: initfsencoding: Unable to get the locale encoding
Traceback (most recent call last):
  File "/opt/hpcc/CPU/anaconda/3-5.3.1/lib/python3.7/encodings/__init__.py", line 31, in <module>
ModuleNotFoundError: No module named 'codecs'
Fatal Python error: initfsencoding: Unable to get the locale encoding
Traceback (most recent call last):
  File "/opt/hpcc/CPU/anaconda/3-5.3.1/lib/python3.7/encodings/__init__.py", line 31, in <module>
Fatal Python error: initfsencoding: Unable to get the locale encoding
Traceback (most recent call last):
  File "/opt/hpcc/CPU/anaconda/3-5.3.1/lib/python3.7/encodings/__init__.py", line 31, in <module>
Fatal Python error: initfsencoding: Unable to get the locale encoding
Traceback (most recent call last):
  File "/opt/hpcc/CPU/anaconda/3-5.3.1/lib/python3.7/encodings/__init__.py", line 31, in <module>
Fatal Python error: initfsencoding: Unable to get the locale encoding
Traceback (most recent call last):
  File "/opt/hpcc/CPU/anaconda/3-5.3.1/lib/python3.7/encodings/__init__.py", line 31, in <module>
ModuleNotFoundError: No module named 'codecs'
ModuleNotFoundError: No module named 'codecs'
ModuleNotFoundError: No module named 'codecs'
ModuleNotFoundError: No module named 'codecs'
Fatal Python error: initfsencoding: Unable to get the locale encoding
Traceback (most recent call last):
  File "/opt/hpcc/CPU/anaconda/3-5.3.1/lib/python3.7/encodings/__init__.py", line 31, in <module>
Fatal Python error: initfsencoding: Unable to get the locale encoding
Traceback (most recent call last):
  File "/opt/hpcc/CPU/anaconda/3-5.3.1/lib/python3.7/encodings/__init__.py", line 31, in <module>
Fatal Python error: initfsencoding: Unable to get the locale encoding
Traceback (most recent call last):
  File "/opt/hpcc/CPU/anaconda/3-5.3.1/lib/python3.7/encodings/__init__.py", line 31, in <module>
srun: error: saliksik-gpu-04: tasks 0-3,11: Aborted
Fatal Python error: initfsencoding: Unable to get the locale encoding
Traceback (most recent call last):
  File "/opt/hpcc/CPU/anaconda/3-5.3.1/lib/python3.7/encodings/__init__.py", line 31, in <module>
Fatal Python error: initfsencoding: Unable to get the locale encoding
Traceback (most recent call last):
  File "/opt/hpcc/CPU/anaconda/3-5.3.1/lib/python3.7/encodings/__init__.py", line 31, in <module>
Fatal Python error: initfsencoding: Unable to get the locale encoding
Traceback (most recent call last):
  File "/opt/hpcc/CPU/anaconda/3-5.3.1/lib/python3.7/encodings/__init__.py", line 31, in <module>
Fatal Python error: initfsencoding: Unable to get the locale encoding
Traceback (most recent call last):
  File "/opt/hpcc/CPU/anaconda/3-5.3.1/lib/python3.7/encodings/__init__.py", line 31, in <module>
ModuleNotFoundError: No module named 'codecs'
ModuleNotFoundError: No module named 'codecs'
ModuleNotFoundError: No module named 'codecs'
ModuleNotFoundError: No module named 'codecs'
ModuleNotFoundError: No module named 'codecs'
ModuleNotFoundError: No module named 'codecs'
ModuleNotFoundError: No module named 'codecs'
srun: error: saliksik-gpu-04: tasks 4-10: Aborted
