>> anaconda-3-5.3.1 has been loaded.
>> python-3.8.2 has been loaded.
>> cuda-10.1_cudnn-7.6.5 has been loaded.
Could not install packages due to an EnvironmentError: [Errno 2] No such file or directory: '/home/arlan.uy/.local/lib/python3.7/site-packages/lazy_object_proxy/cext.c'

Could not install packages due to an EnvironmentError: [Errno 2] No such file or directory: '/home/arlan.uy/.local/lib/python3.7/site-packages/lazy_object_proxy/cext.c'

Could not install packages due to an EnvironmentError: [Errno 2] No such file or directory: '/home/arlan.uy/.local/lib/python3.7/site-packages/lazy_object_proxy/cext.c'

Could not install packages due to an EnvironmentError: [Errno 2] No such file or directory: '/home/arlan.uy/.local/lib/python3.7/site-packages/astroid/__init__.py'

You are using pip version 10.0.1, however version 21.1.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
You are using pip version 10.0.1, however version 21.1.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
You are using pip version 10.0.1, however version 21.1.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
srun: error: saliksik-cpu-21: tasks 2,4,6: Exited with exit code 1
Could not install packages due to an EnvironmentError: [Errno 2] No such file or directory

You are using pip version 10.0.1, however version 21.1.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
srun: error: saliksik-cpu-21: task 1: Exited with exit code 1
You are using pip version 10.0.1, however version 21.1.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
srun: error: saliksik-cpu-21: task 5: Exited with exit code 1
Could not install packages due to an EnvironmentError: [Errno 2] No such file or directory: '/home/arlan.uy/.local/lib/python3.7/site-packages/astroid/interpreter/_import/__pycache__/__init__.cpython-37.pyc'

You are using pip version 10.0.1, however version 21.1.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
srun: error: saliksik-cpu-21: task 0: Exited with exit code 1
You are using pip version 10.0.1, however version 21.1.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
You are using pip version 10.0.1, however version 21.1.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Traceback (most recent call last):
  File "src/abstracts/gpu_selection.py", line 1, in <module>
    import pycuda.autoinit
  File "/home/arlan.uy/.local/lib/python3.7/site-packages/pycuda/autoinit.py", line 5, in <module>
    cuda.init()
pycuda._driver.Error: cuInit failed: unknown error
Traceback (most recent call last):
  File "src/abstracts/gpu_selection.py", line 1, in <module>
    import pycuda.autoinit
  File "/home/arlan.uy/.local/lib/python3.7/site-packages/pycuda/autoinit.py", line 5, in <module>
    cuda.init()
pycuda._driver.Error: cuInit failed: unknown error
Traceback (most recent call last):
  File "src/abstracts/gpu_selection.py", line 1, in <module>
    import pycuda.autoinit
  File "/home/arlan.uy/.local/lib/python3.7/site-packages/pycuda/autoinit.py", line 5, in <module>
    cuda.init()
pycuda._driver.Error: cuInit failed: unknown error
Traceback (most recent call last):
  File "src/abstracts/gpu_selection.py", line 1, in <module>
    import pycuda.autoinit
  File "/home/arlan.uy/.local/lib/python3.7/site-packages/pycuda/autoinit.py", line 5, in <module>
    cuda.init()
pycuda._driver.Error: cuInit failed: unknown error
Traceback (most recent call last):
  File "src/abstracts/gpu_selection.py", line 1, in <module>
    import pycuda.autoinit
  File "/home/arlan.uy/.local/lib/python3.7/site-packages/pycuda/autoinit.py", line 5, in <module>
    cuda.init()
pycuda._driver.Error: cuInit failed: unknown error
Traceback (most recent call last):
  File "src/abstracts/gpu_selection.py", line 1, in <module>
    import pycuda.autoinit
  File "/home/arlan.uy/.local/lib/python3.7/site-packages/pycuda/autoinit.py", line 5, in <module>
    cuda.init()
pycuda._driver.Error: cuInit failed: unknown error
Traceback (most recent call last):
  File "src/abstracts/gpu_selection.py", line 1, in <module>
    import pycuda.autoinit
  File "/home/arlan.uy/.local/lib/python3.7/site-packages/pycuda/autoinit.py", line 5, in <module>
    cuda.init()
pycuda._driver.Error: cuInit failed: unknown error
Traceback (most recent call last):
  File "src/abstracts/gpu_selection.py", line 1, in <module>
    import pycuda.autoinit
  File "/home/arlan.uy/.local/lib/python3.7/site-packages/pycuda/autoinit.py", line 5, in <module>
    cuda.init()
pycuda._driver.Error: cuInit failed: unknown error
srun: error: saliksik-cpu-21: tasks 0-7: Exited with exit code 1
